apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: car-showcase-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: car-showcase-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
