apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-showcase-app-deployment
  labels:
    app: car-showcase-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-showcase-app
  template:
    metadata:
      labels:
        app: car-showcase-app
    spec:
      containers:
        - name: car-showcase-app-container
          image: krish010/luxury-car-app:latest  # This should be the latest Docker image you've pushed
          ports:
            - containerPort: 3000  # Express app default port
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

