apiVersion: v1
kind: Service
metadata:
  name: car-showcase-app-service
  labels:
    app: car-showcase-app
spec:
  selector:
    app: car-showcase-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

