name: Build, Push & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: docker build -t 084828567677.dkr.ecr.ap-south-1.amazonaws.com/car-web-app:latest .

    - name: Push Docker image to ECR
      run: docker push 084828567677.dkr.ecr.ap-south-1.amazonaws.com/car-web-app:latest

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull 084828567677.dkr.ecr.ap-south-1.amazonaws.com/car-web-app:latest
          docker stop $(docker ps -q) || true
          docker run -d -p 3000:3000 084828567677.dkr.ecr.ap-south-1.amazonaws.com/car-web-app:latest
