name: Build and Deploy Car Web App to EKS (ECR)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 084828567677.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t car-showcase-app .
        docker tag car-showcase-app:latest 084828567677.dkr.ecr.ap-south-1.amazonaws.com/car-showcase-app:latest

    - name: Push Image to ECR
      run: |
        docker push 084828567677.dkr.ecr.ap-south-1.amazonaws.com/car-showcase-app:latest

    - name: Set up kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name luxury-car-eks

    - name: Deploy to EKS
      run: |
        kubectl rollout restart deployment car-showcase-app-deployment

    - name: Deploy YAML Manifests
      run: |
        kubectl apply -f kubernetes/
