name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/car-web-app
            git pull origin main
            npm install
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            pm2 stop all || true
            pm2 start server.js --name car-showcase-app
